services:
    nodered:
        container_name: nodered
        image: william1608/node-red-ffmpeg:$VERSION
        environment:
         - TZ=Europe/Rome
         - NODE_RED_ENABLE_SAFE_MODE='false'
        ports:
        - "1881:1880"
        volumes:
        - ./data:/data
